# Generated by Django 4.1.3 on 2022-12-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_phone_number"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="user",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="user_profile",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
            preserve_default=False,
        ),
    ]
