# Generated by Django 4.1.3 on 2022-12-15 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0002_remove_restaurant_user_restaurant_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
