# Generated by Django 4.1.3 on 2022-12-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profile_user"),
        ("restaurants", "0003_remove_restaurant_user_profile_restaurant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="user_profile",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
            preserve_default=False,
        ),
    ]
