# Generated by Django 4.1.3 on 2022-12-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_restaurant_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="user_profile",
        ),
    ]
