# Generated by Django 4.1.3 on 2022-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="address_line_2",
        ),
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
